# Generated by Django 3.2.16 on 2023-04-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('client_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('name', models.CharField(max_length=511, verbose_name='Название')),
                ('mon_start_time', models.TimeField(verbose_name='Время начала ПН')),
                ('mon_end_time', models.TimeField(verbose_name='Время окончания ПН')),
                ('tue_start_time', models.TimeField(verbose_name='Время начала ВТ')),
                ('tue_end_time', models.TimeField(verbose_name='Время окончания ВТ')),
                ('wed_start_time', models.TimeField(verbose_name='Время начала СР')),
                ('wed_end_time', models.TimeField(verbose_name='Время окончания СР')),
                ('thu_start_time', models.TimeField(verbose_name='Время начала ЧТ')),
                ('thu_end_time', models.TimeField(verbose_name='Время окончания ЧТ')),
                ('fri_start_time', models.TimeField(verbose_name='Время начала ПТ')),
                ('fri_end_time', models.TimeField(verbose_name='Время окончания ПТ')),
                ('sat_start_time', models.TimeField(verbose_name='Время начала СБ')),
                ('sat_end_time', models.TimeField(verbose_name='Время окончания СБ')),
                ('sun_start_time', models.TimeField(verbose_name='Время начала ВС')),
                ('sun_end_time', models.TimeField(verbose_name='Время окончания ВС')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатуры',
            },
        ),
        migrations.CreateModel(
            name='ApiName',
            fields=[
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='api_names', serialize=False, to='nomenclature.nomenclature', unique=True, verbose_name='ID')),
                ('last_answer_time_date', models.DateTimeField(blank=True, null=True, verbose_name='Последнее время ответа в API')),
                ('name', models.CharField(max_length=511, verbose_name='Имя в API')),
            ],
            options={
                'verbose_name': 'API имя',
                'verbose_name_plural': 'API имена',
            },
        ),
        migrations.CreateModel(
            name='IndividualGraphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('date', models.DateField(verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to='nomenclature.nomenclature', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Индивидуальный график',
                'verbose_name_plural': 'Индивидуальные графики',
            },
        ),
    ]
