# Generated by Django 3.2.16 on 2023-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0002_nomenclature_time_zone'),
    ]
