# Generated by Django 3.2.16 on 2023-04-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwInfo',
            fields=[
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nomenclature.nomenclature', unique=True, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=511, null=True, verbose_name='Город')),
                ('model', models.CharField(blank=True, max_length=511, null=True, verbose_name='Модель')),
                ('provider', models.CharField(blank=True, max_length=511, null=True, verbose_name='Провайдер')),
                ('ext_ip', models.CharField(blank=True, max_length=63, null=True, verbose_name='Внешний IP')),
            ],
            options={
                'verbose_name': 'Информация об оборудовании',
                'verbose_name_plural': 'Информация об оборудовании',
            },
        ),
        migrations.CreateModel(
            name='NetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=511, verbose_name='Интерфейс')),
                ('mac', models.CharField(max_length=63, verbose_name='Мак адресс')),
                ('ip', models.CharField(max_length=63, verbose_name='IP адресс')),
                ('hw_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='harvest.hwinfo', verbose_name='hw_info_id')),
            ],
            options={
                'verbose_name': 'Интернет конфигурация',
                'verbose_name_plural': 'Интернет конфигурация',
            },
        ),
        migrations.CreateModel(
            name='AudioDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.PositiveSmallIntegerField(verbose_name='Номер карты')),
                ('device_name', models.CharField(max_length=511, verbose_name='Имя карты')),
                ('device_item', models.CharField(blank=True, max_length=63, null=True, verbose_name='Имя регулировки')),
                ('hw_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_devices', to='harvest.hwinfo', verbose_name='hw_info_id')),
            ],
            options={
                'verbose_name': 'Звуковая карта',
                'verbose_name_plural': 'Звуковые карты',
            },
        ),
    ]
