# Generated by Django 3.2.16 on 2023-04-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomenclatureStatus',
            fields=[
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nomenclature.nomenclature', unique=True, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Доступна'), (2, 'Недоступна по графику'), (3, 'Недоступна')], default=1, verbose_name='Статус')),
                ('answer_time', models.DateTimeField(verbose_name='Последнее время ответа')),
            ],
            options={
                'verbose_name': 'Статус доступности',
                'verbose_name_plural': 'Статусы доступности',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_delta_available', models.PositiveSmallIntegerField(verbose_name='Период доступности секунд')),
            ],
        ),
        migrations.CreateModel(
            name='NomenclatureStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_status', models.PositiveSmallIntegerField(choices=[(1, 'Доступна'), (2, 'Недоступна по графику'), (3, 'Недоступна')], verbose_name='Статус после изменеения')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='Время изменеения статуса')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='nomenclature.nomenclature', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
            },
        ),
    ]
