# Generated by Django 3.2.16 on 2023-06-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avail', '0002_alter_nomenclaturestatus_answer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclaturestatus',
            name='answer_time',
            field=models.DateTimeField(verbose_name='Последнее время ответа'),
        ),
    ]
