# Generated by Django 4.0.2 on 2022-10-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField()),
                ('hash', models.CharField(max_length=32)),
                ('start_at', models.DateTimeField()),
                ('length', models.PositiveIntegerField()),
            ],
        ),
    ]
