# Generated by Django 4.0.2 on 2022-10-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_adstat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adstat',
            options={'verbose_name': 'Статистика рекламы', 'verbose_name_plural': 'Статистика рекламы'},
        ),
        migrations.AlterModelOptions(
            name='bgstat',
            options={'verbose_name': 'Статистика музыки', 'verbose_name_plural': 'Статистика музыки'},
        ),
        migrations.AlterField(
            model_name='bgstat',
            name='client_id',
            field=models.PositiveIntegerField(verbose_name='ID'),
        ),
    ]
