# Generated by Django 4.1.3 on 2022-11-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_adstat_time_block_alter_adstat_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adstat',
            name='file_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='ID роилка'),
        ),
        migrations.AddField(
            model_name='bgstat',
            name='file_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='ID роилка'),
        ),
    ]
