# Generated by Django 3.2.16 on 2023-02-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_adstat_file_id_bgstat_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ad', models.BooleanField(verbose_name='Является рекламой')),
                ('client_id', models.PositiveIntegerField(verbose_name='ID машины')),
                ('hash', models.CharField(max_length=32, verbose_name='Контрольная сумма ролика')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.PositiveIntegerField(verbose_name='Количество выходов за день')),
            ],
            options={
                'verbose_name': 'Количество выходов',
                'verbose_name_plural': 'Количество выходов',
            },
        ),
        migrations.CreateModel(
            name='TwoDaysAdStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='ID')),
                ('hash', models.CharField(max_length=32, verbose_name='Контрольная сумма ролика')),
                ('start_at', models.DateTimeField(verbose_name='Датаи время начала вещания')),
                ('length', models.PositiveIntegerField(verbose_name='Хронометраж')),
                ('time_block', models.TimeField(null=True, verbose_name='блок вещания ролика')),
                ('file_id', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='ID роилка')),
            ],
            options={
                'verbose_name': 'Статистика рекламы за 2 дня',
                'verbose_name_plural': 'Статистика рекламы за 2 дня',
            },
        ),
        migrations.CreateModel(
            name='TwoDaysBgStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='ID')),
                ('hash', models.CharField(max_length=32, verbose_name='Контрольная сумма ролика')),
                ('start_at', models.DateTimeField(verbose_name='Дата и время начала вещания')),
                ('length', models.PositiveIntegerField(verbose_name='Хронометраж')),
                ('file_id', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='ID роилка')),
            ],
            options={
                'verbose_name': 'Статистика музыки за 2 дня',
                'verbose_name_plural': 'Статистика музыки за 2 дня',
            },
        ),
    ]
